title: Tannous Kass-Hanna
description: Economist â€“ macroeconomic policy, emerging markets, and international economics
url: https://tkasshanna.github.io
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Tannous Kass-Hanna
social:
  name: Tannous Kass-Hanna
  links:
    - https://www.linkedin.com/in/tannouskasshanna
    - https://scholar.google.com/citations?user=bHqrBfoAAAAJ&hl=en
